#!/usr/bin/env python3
"""Compile every Rust snippet in the Markdown documentation.

`cargo test --doc` covers the examples inside `src/`, and nothing covered the
ones on the website or in the README — which is why several of them went on
calling `build()` and `possible_children` for a whole afternoon after those
names changed. This closes that gap: every ```rust block in `docs/` and
`README.md` is extracted, wrapped the way rustdoc wraps a doctest, and handed
to `cargo check`.

Snippets are checked, not run, for the same reason most of them are `no_run`
in rustdoc: they open files that are not there. What matters is that they
still typecheck against the crate as it is today.

Conventions, matching rustdoc's:

- A line beginning `# ` is setup the reader does not need to see. Write the
  setup rather than leaving a snippet that cannot compile — a fragment that
  refers to an undefined `schemas` is a snippet nobody can paste.
- ```rust is checked. ```text, ```python, ```toml and ```console are not.
- A block tagged ```rust,ignore is skipped, for the rare snippet that is
  deliberately not real code. Use it sparingly; it switches the guard off.

Run it directly, or let CI do it:

    python3 scripts/check-doc-snippets.py
"""

from __future__ import annotations

import re
import subprocess
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# Cargo only compiles what is under `examples/`, so the generated file has to
# live there. It is written, checked, and deleted again, so nobody ever finds
# a stale one and wonders where it came from.
GENERATED = ROOT / "examples" / "doc_snippets.rs"

FENCE = re.compile(r"^(?P<indent>[ \t]*)```rust(?P<info>[^\n]*)$")


def sources() -> list[Path]:
    """Every hand-written Markdown file. `docs/rust/` is generated rustdoc."""
    files = [p for p in sorted(ROOT.joinpath("docs").rglob("*.md")) if "rust" not in p.parts]
    return [ROOT / "README.md", *files]


def blocks(path: Path) -> list[tuple[int, str]]:
    """Every ```rust block, with its 1-based line number.

    Indentation is stripped because MkDocs' content tabs indent a fence by
    four spaces, which is exactly the shape a naive extractor mangles.
    """
    lines = path.read_text().split("\n")
    found: list[tuple[int, str]] = []
    i = 0
    while i < len(lines):
        m = FENCE.match(lines[i])
        if not m:
            i += 1
            continue
        indent, info = m.group("indent"), m.group("info")
        if "ignore" in info:
            i += 1
            continue
        start = i + 1
        j = start
        while j < len(lines) and lines[j].strip() != "```":
            j += 1
        body = [ln[len(indent) :] if ln.startswith(indent) else ln for ln in lines[start:j]]
        found.append((start + 1, "\n".join(body)))
        i = j + 1
    return found


def unhide(code: str) -> str:
    """Reveal rustdoc's hidden setup lines, so they compile with the rest."""
    out = []
    for line in code.split("\n"):
        stripped = line.lstrip()
        pad = line[: len(line) - len(stripped)]
        if stripped.startswith("# "):
            out.append(pad + stripped[2:])
        elif stripped == "#":
            out.append("")
        else:
            out.append(line)
    return "\n".join(out)


def wrap(code: str) -> str:
    """Give the snippet a body to live in, the way rustdoc gives it a `main`.

    Called `run` rather than `main`: the generated file is a cargo example,
    which needs exactly one `main` and that one at the crate root.
    """
    if re.search(r"\bfn main\b", code):
        return re.sub(r"\bfn main\b", "fn run", code)
    body = code.rstrip()
    # A snippet that ends by naming its error type is telling us what `main`
    # should return; `?` without that means the type is ours to pick.
    typed = re.search(r"Ok::<\s*_\s*,\s*(.+?)\s*>\(\(\)\)\s*$", body)
    if typed:
        ret, tail = f"Result<(), {typed.group(1)}>", ""
    elif "?" in body:
        ret, tail = "Result<(), Box<dyn std::error::Error>>", "\n    Ok(())"
    else:
        ret, tail = "()", ""
    return f"pub fn run() -> {ret} {{\n{textwrap.indent(body, '    ')}{tail}\n}}"


def main() -> int:
    snippets = [(p, line, code) for p in sources() for line, code in blocks(p)]
    if not snippets:
        print("no Rust snippets found — has the extractor stopped matching?", file=sys.stderr)
        return 1

    header = (
        "//! Generated by scripts/check-doc-snippets.py. Do not edit.\n"
        "#![allow(unused)]\n\n"
        "fn main() {}\n\n"
    )
    out = [header]
    # Where each snippet lands in the generated file, so an error can be
    # reported against the Markdown a reader would have to fix.
    spans: list[tuple[int, int, str]] = []
    at = header.count("\n") + 1
    for n, (path, line, code) in enumerate(snippets):
        rel = path.relative_to(ROOT)
        module = (
            f"// {rel}:{line}\n"
            f"#[allow(unused, clippy::all)]\n"
            f"pub mod snippet_{n} {{\n"
            f"    #[allow(unused_imports)]\n"
            f"    use xsdkit::*;\n"
            f"{textwrap.indent(wrap(unhide(code)), '    ')}\n"
            f"}}\n\n"
        )
        spans.append((at, at + module.count("\n"), f"{rel}:{line}"))
        at += module.count("\n")
        out.append(module)

    GENERATED.write_text("".join(out))
    print(f"checking {len(snippets)} Rust snippets from {len(sources())} files")
    try:
        result = subprocess.run(
            # The serde examples need the feature that makes them true.
            ["cargo", "check", "--features", "serde", "--quiet", "--example", "doc_snippets"],
            cwd=ROOT,
            capture_output=True,
            text=True,
        )
    finally:
        GENERATED.unlink(missing_ok=True)

    if result.returncode == 0:
        print("all snippets compile")
        return 0

    generated_line = re.compile(r"doc_snippets\.rs:(\d+)")
    for line in result.stderr.splitlines():
        print(line)
        m = generated_line.search(line)
        if not m:
            continue
        n = int(m.group(1))
        origin = next((o for lo, hi, o in spans if lo <= n <= hi), None)
        if origin:
            print(f"   ^ this snippet is {origin}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
