#!/usr/bin/env python3
"""Render `tests/conformance/spec-rules.tsv` as `docs/project/spec-rules.md`.

The table is data, and the published page is a view of it. Generating the page
means the two cannot disagree; `--check` is what CI runs, so a re-judged row
that is not re-rendered fails there rather than on the website.

    scripts/render-spec-rules.py            # write the page
    scripts/render-spec-rules.py --check    # fail if it is out of date
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TSV = ROOT / "tests" / "conformance" / "spec-rules.tsv"
PAGE = ROOT / "docs" / "project" / "spec-rules.md"

REC = {
    "structures": "https://www.w3.org/TR/xmlschema11-1/",
    "datatypes": "https://www.w3.org/TR/xmlschema11-2/",
}
TITLE = {"structures": "Part 1: Structures", "datatypes": "Part 2: Datatypes"}
# Most specific first: the kinds are printed in this order.
KINDS = [
    "Schema Component Constraint",
    "Schema Representation Constraint",
    "Validation Rule",
    "Schema Information Set Contribution",
    "Constraint",
]
MARK = {
    "yes": "yes",
    "partial": "partial",
    "no": "**no**",
    "by-construction": "by construction",
}


def rows():
    out = []
    for line in TSV.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        f = line.split("\t")
        if len(f) != 8:
            sys.exit(f"expected 8 columns: {line}")
        out.append(
            dict(
                zip(
                    ["spec", "anchor", "kind", "name", "status", "site", "note", "fixtures"],
                    f,
                )
            )
        )
    return out


def render(rs) -> str:
    n = len(rs)
    count = {k: sum(1 for r in rs if r["status"] == k) for k in MARK}
    L = []
    L.append("# Which rules of the specification are enforced")
    L.append("")
    L.append("<!-- Generated by scripts/render-spec-rules.py from")
    L.append("     tests/conformance/spec-rules.tsv. Edit the table, not this page. -->")
    L.append("")
    L.append(
        "XSD is not one rule but **%d**, each of them named and numbered by the\n"
        "specification itself: Appendix B of each Recommendation is, in effect, an\n"
        "index of them. That makes the language a finite checklist rather than a\n"
        "document you can only read, and this page is that checklist with a column\n"
        "for what `xsdkit` does about each entry." % n
    )
    L.append("")
    L.append(
        "| enforced | rules |\n|---|---|\n"
        "| yes | %d |\n| in part | %d |\n| no | %d |\n| nothing to enforce | %d |"
        % (count["yes"], count["partial"], count["no"], count["by-construction"])
    )
    L.append("")
    L.append(
        "**This is not code coverage, and the difference is the point.** Region\n"
        "coverage says how much of what was written gets run; it is silent on a rule\n"
        "nobody wrote. Nor can the W3C suite answer it: the schema half offers only\n"
        "about 220 negative cases per version to share among 66 Schema Component\n"
        "Constraints, so a rule can be entirely absent and cost a percentage point.\n"
        "The table below is the answer to *which parts of XSD does this enforce*,\n"
        "which is the question a schema author actually has."
    )
    L.append("")
    L.append(
        "A rule marked **no** is a rule this crate does not check. It is not a bug\n"
        "report — several are deliberate, and the four *nothing to enforce* rows\n"
        "constrain the shape of a component in ways this loader cannot produce — but\n"
        "it does mean a schema `xsdkit` accepts is not thereby a valid schema."
    )
    L.append("")
    L.append(
        "The rule columns are generated from the Recommendations\n"
        "(`scripts/extract-spec-rules.py`); the judgement columns are maintained by\n"
        "hand and gated by `tests/spec_rules/main.rs`, which requires every claim to\n"
        "name a site and every diagnostic code to be attributable to a row here."
    )
    L.append("")
    L.append(
        "A ✓ in the last column means this crate has its **own** fixtures for the\n"
        "rule — the smallest schema that violates it, and a near-miss that must still\n"
        "load — in `tests/spec_rules/fixtures.rs`. %d of %d rules so far. The W3C\n"
        "suite cannot supply those: it offers about 220 negative schema cases per\n"
        "version to share among 66 Schema Component Constraints, so a rule can be\n"
        "enforced by a check nobody has ever seen fire." % (
            sum(1 for r in rs if r["fixtures"] == "fixtures"), n)
    )

    for spec in ("structures", "datatypes"):
        group = [r for r in rs if r["spec"] == spec]
        L.append("")
        L.append("## %s" % TITLE[spec])
        L.append("")
        L.append("%d rules, of which %d enforced." % (
            len(group), sum(1 for r in group if r["status"] == "yes")))
        for kind in KINDS:
            here = [r for r in group if r["kind"] == kind]
            if not here:
                continue
            L.append("")
            L.append("### %s%s" % (kind, "" if kind.endswith("s") else "s"))
            L.append("")
            L.append("| Rule | Enforced | Where, and what is missing | Fixtures |")
            L.append("|---|---|---|---|")
            for r in sorted(here, key=lambda r: r["name"].lower()):
                link = "[%s](%s#%s)" % (r["name"], REC[r["spec"]], r["anchor"])
                where = ""
                if r["site"] not in ("-", ""):
                    where = "`%s`" % r["site"]
                if r["note"]:
                    where = ("%s — %s" % (where, r["note"])) if where else r["note"]
                L.append(
                    "| %s | %s | %s | %s |"
                    % (
                        link,
                        MARK[r["status"]],
                        where or "—",
                        "✓" if r["fixtures"] == "fixtures" else "",
                    )
                )
    L.append("")
    return "\n".join(L)


def main() -> int:
    text = render(rows())
    if "--check" in sys.argv:
        current = PAGE.read_text(encoding="utf-8") if PAGE.is_file() else ""
        if current == text:
            print(f"{PAGE.relative_to(ROOT)} is up to date")
            return 0
        print(f"{PAGE.relative_to(ROOT)} is out of date. Regenerate it with:")
        print("    scripts/render-spec-rules.py")
        return 1
    PAGE.write_text(text, encoding="utf-8")
    print(f"wrote {PAGE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
